package com.syaru.ae2craftingoptimizer.golden;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;

final class CanonicalFixtureGoldenTest {
    private static final Path GOLDEN_FILE = Path.of(
            "src",
            "test",
            "resources",
            "aco",
            "golden",
            "fixtures.jsonl");

    @Test
    void allFixturesMatchReviewableGoldenOutput() throws IOException {
        Map<String, String> expected = readGolden();
        Map<String, String> actual = new HashMap<>();
        for (CanonicalCraftingFixture fixture : CanonicalFixtureCatalog.all()) {
            CanonicalCraftingResult reference = CanonicalCraftingEvaluator.reference(fixture);
            CanonicalCraftingResult optimized = CanonicalCraftingEvaluator.optimized(fixture);
            assertEquals(
                    reference.toCanonicalJson(),
                    optimized.toCanonicalJson(),
                    "optimized fixture result diverged from the reference: " + fixture.id());
            actual.put(fixture.id(), reference.toCanonicalJson());
        }
        if (Boolean.getBoolean("aco.updateGolden")) {
            writeGolden(actual);
            return;
        }
        assertEquals(CanonicalFixtureCatalog.all().size(), expected.size());
        assertEquals(actual, expected);
    }

    @Test
    void fixtureCatalogDoesNotDependOnMapIterationOrder() {
        List<CanonicalCraftingFixture> fixtures = CanonicalFixtureCatalog.all();
        for (CanonicalCraftingFixture fixture : fixtures) {
            CanonicalCraftingResult result = CanonicalCraftingEvaluator.reference(fixture);
            assertEquals(result.toCanonicalJson(), result.toCanonicalJson());
            assertTrue(result.payloadDigest().matches("[0-9a-f]{64}"));
        }
    }

    private static Map<String, String> readGolden() throws IOException {
        if (!Files.isRegularFile(GOLDEN_FILE)) {
            throw new AssertionError(
                    "Golden fixture file is missing; use the explicit updateGoldenFixtures task");
        }
        Map<String, String> result = new HashMap<>();
        for (String line : Files.readAllLines(GOLDEN_FILE, StandardCharsets.UTF_8)) {
            if (line.isBlank() || line.startsWith("#")) {
                continue;
            }
            int separator = line.indexOf('\t');
            if (separator <= 0) {
                throw new AssertionError("malformed golden fixture line");
            }
            if (result.put(line.substring(0, separator), line.substring(separator + 1)) != null) {
                throw new AssertionError("duplicate golden fixture id");
            }
        }
        return result;
    }

    private static void writeGolden(Map<String, String> actual) throws IOException {
        Files.createDirectories(GOLDEN_FILE.getParent());
        StringBuilder output = new StringBuilder(
                "# Explicitly generated by updateGoldenFixtures; normal tests never overwrite this file.\n");
        actual.entrySet().stream()
                .sorted(Map.Entry.comparingByKey())
                .forEach(entry -> output.append(entry.getKey()).append('\t').append(entry.getValue()).append('\n'));
        Files.writeString(GOLDEN_FILE, output, StandardCharsets.UTF_8);
    }
}
