package com.syaru.ae2craftingoptimizer.optimization;

/** BigInteger計画を採用できなかった理由を、ログと統計で安定して識別するコード。 */
public enum BigIntegerPlanDeclineReason {
    DISABLED,
    INVALID_REQUEST,
    NO_COMPILED_PROGRAM,
    UNSUPPORTED_TOPOLOGY,
    INCOMPLETE_INVENTORY,
    SHADOW_NOT_QUALIFIED,
    GENERATION_CHANGED,
    INVENTORY_CHANGED,
    TOPOLOGY_CHANGED,
    MISSING_SIMULATION,
    EXECUTION_WINDOW_UNAVAILABLE,
    EXECUTION_DISABLED,
    STORAGE_ROUTE_UNAVAILABLE,
    PLAN_NOT_PROVEN,
    SUBMISSION_BACKING_MISSING,
    CANCELLED,
    ARITHMETIC_FAILURE,
    INTERNAL_FAILURE
}
